Fix example tailwind
fix:
╰─>$ cargo leptos watch
Error: at `…/cargo-leptos-0.0.9/src/main.rs@104:58`

Caused by:
    no css/sass/scss file found at: "style/output.css"